title = "sysrqmagician's homepage"
description = "A collection of showcases and ramblings"

base_url = "https://sysrqmagician.dev"
theme = "zola-bearblog-sysrq"

compile_sass = false
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
  { name = "tag", feed = true },
]

[markdown]
highlight_code = true

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"


[extra]
hide_made_with_line = true

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Projects"
url = "@/projects/_index.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

[[extra.footer_menu]]
name = "RSS Feed"
url = "/atom.xml"

