# The URL the site will be built for
base_url = "https://sysrqmagician.dev"
theme = "zola-bearblog"

compile_sass = false
build_search_index = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"


[extra]

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Projects"
url = "@/projects.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

